title: Louis Dotfiles

groups:
  - title: Zsh
    modules:
      - title: Zsh configuration
        script: modules/zsh/core/install.sh
        default: true

      - title: Zsh plugins
        script: modules/zsh/plugins/install.sh
        default: true

      - title: XBPS sync helper
        script: modules/zsh/xbps-sync/install.sh
        default: true
        
  - title: Plasma
    modules: 
      - title: Krohnkite Tiling Manager
        script: modules/plasma/kwin/krohnkite/install.sh
        default: true

      - title: Geometry Change KWin effects
        script: modules/plasma/kwin/geometry-change/install.sh
        default: true

      - title: Fusion panel - Top panel
        script: modules/plasma/panel/install.sh
        default: true

      - title: Shortcuts
        default: true
        modules:
          - title: Clear all shortcuts
            script: modules/plasma/shortcuts/clear.sh
            default: true

          - title: Applications shortcuts
            script: modules/plasma/shortcuts/set-apps.sh
            default: true

          - title: Function keys
            script: modules/plasma/shortcuts/set-functions.sh
            default: true

          - title: Shell management shortcuts
            script: modules/plasma/shortcuts/set-shell.sh
            default: true

          - title: Window management shortcuts
            script: modules/plasma/shortcuts/set-wm.sh
            default: true
      
  - title: Secure boot and encryption utilities
    modules:
      - title: Sbctl batch signing
        script: modules/secure-boot-encrypt/sbctl/install.sh
        default: false

      - title: UKI gen
        default: false
        modules:
          - title: Add ukigen helper script
            script: modules/secure-boot-encrypt/ukigen/install.sh
            default: true

          - title: Replace default 20-initramfs with 20-ukigen
            script: modules/secure-boot-encrypt/ukigen/hook/install.sh
            default: true